use_frameworks!

platform :ios, '9.0'

target 'JHNTableViewSwipe_Example' do
  pod 'JHNTableViewSwipe', :path => '../'

  target 'JHNTableViewSwipe_Tests' do
    inherit! :search_paths

    
  end
end
